export default {
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "Flt Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 40,
      brand: "Nike",
      rating: 4.5,
      numReviews: 5,
      countInStock: 15,
    },
    {
      _id: "3",
      name: "Best Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 100,
      brand: "Nike",
      rating: 4.5,
      numReviews: 50,
      countInStock: 3,
    },
    {
      _id: "4",
      name: "Good Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 100,
      brand: "Nike",
      rating: 4.5,
      numReviews: 50,
      countInStock: 2,
    },
  ],
};
